# Generated by Django 5.1.15 on 2026-04-19 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AffectLexiconEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(max_length=80, unique=True)),
                (
                    "polarity",
                    models.CharField(
                        choices=[
                            ("positive", "Tích cực"),
                            ("negative", "Tiêu cực"),
                            ("neutral", "Trung tính"),
                        ],
                        max_length=16,
                    ),
                ),
                ("valence_weight", models.FloatField(default=0.0)),
                ("arousal_weight", models.FloatField(default=0.0)),
                ("language", models.CharField(default="vi", max_length=8)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "palp_affect_lexicon",
                "ordering": ["term"],
            },
        ),
        migrations.CreateModel(
            name="AffectSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("keystroke", "Bàn phím"),
                            ("linguistic", "Ngôn ngữ"),
                            ("combined", "Kết hợp"),
                        ],
                        max_length=16,
                    ),
                ),
                ("valence", models.FloatField(default=0.0)),
                ("arousal", models.FloatField(default=0.0)),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Discrete label produced by the engine (engaged, frustrated, …).",
                        max_length=40,
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Engine-specific feature values (sanitised, no raw text).",
                    ),
                ),
                ("text_length", models.PositiveIntegerField(default=0)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="affect_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_affect_snapshot",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "-occurred_at"],
                        name="palp_affect_student_17c236_idx",
                    ),
                    models.Index(
                        fields=["modality", "-occurred_at"],
                        name="palp_affect_modalit_35783a_idx",
                    ),
                ],
            },
        ),
    ]
