# Generated by Django 5.1.15 on 2026-04-19 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0002_concept_uq_concept_course_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField()),
                ("summary", models.TextField()),
                ("highlights", models.JSONField(blank=True, default=list)),
                ("concerns", models.JSONField(blank=True, default=list)),
                ("suggestions", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Bản nháp"),
                            ("sent", "Đã gửi"),
                            ("archived", "Đã lưu trữ"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback_drafts_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_drafts_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_copilot_feedback_draft",
                "indexes": [
                    models.Index(
                        fields=["student", "-week_start"],
                        name="palp_copilo_student_67e1f0_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="palp_copilo_status_be1219_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "week_start", "requested_by"),
                        name="uq_feedback_draft_student_week_author",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GeneratedExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_key", models.SlugField(max_length=80)),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Dễ"), (2, "Trung bình"), (3, "Khó")], default=2
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "body",
                    models.JSONField(
                        default=dict,
                        help_text="{question, options, correct_answer, hints, explanation}",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Bản nháp"),
                            ("reviewed", "Đã review"),
                            ("approved", "Đã duyệt"),
                            ("rejected", "Đã từ chối"),
                            ("published", "Đã xuất bản"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                (
                    "published_micro_task_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_exercises",
                        to="curriculum.concept",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_exercises",
                        to="curriculum.course",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_exercises",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_copilot_generated_exercise",
                "indexes": [
                    models.Index(
                        fields=["course", "concept", "-created_at"],
                        name="palp_copilo_course__e16e83_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="palp_copilo_status_942097_idx",
                    ),
                ],
            },
        ),
    ]
