# Generated by Django 5.1.15 on 2026-04-18 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EpisodicMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("struggle", "Vật lộn với concept"),
                            ("breakthrough", "Đột phá / hiểu ra"),
                            ("reflection", "Phản tỉnh tuần"),
                            ("emergency", "Sự kiện khẩn cấp"),
                            ("peer_session", "Phiên dạy nhau"),
                            ("coach_turn", "Một lượt với coach"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        help_text="One-sentence summary; never the raw message body.",
                        max_length=240,
                    ),
                ),
                (
                    "detail",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured payload (concept_id, score, etc). NEVER a verbatim message.",
                    ),
                ),
                (
                    "salience",
                    models.FloatField(
                        default=0.5,
                        help_text="0..1 — how relevant this episode is for recall.",
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodic_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_memory_episodic",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "-occurred_at"],
                        name="palp_memory_student_02132d_idx",
                    ),
                    models.Index(
                        fields=["student", "kind", "-occurred_at"],
                        name="palp_memory_student_ead8e3_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProceduralMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strategy_key",
                    models.SlugField(
                        help_text="e.g. 'spaced_practice_nudge', 'morning_session', 'peer_session'.",
                        max_length=80,
                    ),
                ),
                ("successes", models.PositiveIntegerField(default=0)),
                ("failures", models.PositiveIntegerField(default=0)),
                (
                    "effectiveness_estimate",
                    models.FloatField(
                        default=0.5,
                        help_text="0..1 — running estimate of P(success | strategy applied).",
                    ),
                ),
                ("last_applied_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procedural_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_memory_procedural",
                "indexes": [
                    models.Index(
                        fields=["student", "-effectiveness_estimate"],
                        name="palp_memory_student_2e2f2e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "strategy_key"),
                        name="uq_procedural_student_strategy",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SemanticMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=80)),
                ("value", models.JSONField(blank=True, default=dict)),
                ("confidence", models.FloatField(default=0.7)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Where the fact came from (goals.career_goal, coach.dialog, …).",
                        max_length=40,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semantic_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_memory_semantic",
                "indexes": [
                    models.Index(
                        fields=["student", "key"], name="palp_memory_student_c21f1b_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "key"), name="uq_semantic_student_key"
                    )
                ],
            },
        ),
    ]
