# Generated by Django 5.1.15 on 2026-04-18 01:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_eventlog_event_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="timestamp_utc",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
