# Generated by Django 5.1.15 on 2026-04-18 03:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_groups_alter_user_is_active_and_more"),
        ("curriculum", "0002_concept_uq_concept_course_order"),
        ("events", "0005_alter_eventlog_timestamp_utc"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="eventlog",
            index=models.Index(
                fields=["actor", "-timestamp_utc"], name="palp_event_actor_ts_desc"
            ),
        ),
    ]
