# Generated by Django 5.1.15 on 2026-04-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_eventlog_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='event_name',
            field=models.CharField(choices=[('session_started', 'Bắt đầu phiên'), ('session_ended', 'Kết thúc phiên'), ('assessment_completed', 'Hoàn thành assessment'), ('assess_answer', 'Trả lời câu hỏi assessment'), ('assess_complete', 'Nộp bài assessment'), ('assess_expired', 'Hết giờ assessment'), ('assess_resumed', 'Tiếp tục assessment'), ('micro_task_completed', 'Hoàn thành micro-task'), ('content_intervention', 'Can thiệp nội dung'), ('retry_triggered', 'Retry triggered'), ('gv_dashboard_viewed', 'GV xem dashboard'), ('gv_action_taken', 'GV thực hiện can thiệp'), ('alert_dismissed', 'Bỏ qua cảnh báo'), ('intervention_created', 'Tạo can thiệp'), ('wellbeing_nudge', 'Nhắc nghỉ'), ('wellbeing_nudge_shown', 'Hiện nhắc nghỉ'), ('wellbeing_nudge_accepted', 'Chấp nhận nghỉ'), ('wellbeing_nudge_dismissed', 'Bỏ qua nhắc nghỉ'), ('page_view', 'Xem trang'), ('etl_started', 'ETL bắt đầu'), ('etl_completed', 'ETL hoàn thành'), ('etl_failed', 'ETL thất bại'), ('focus_lost', 'Mất tập trung'), ('focus_gained', 'Lấy lại tập trung'), ('tab_switched', 'Đổi tab'), ('idle_started', 'Bắt đầu nhàn rỗi'), ('idle_ended', 'Kết thúc nhàn rỗi'), ('scroll_depth', 'Độ cuộn trang'), ('hint_requested', 'Yêu cầu gợi ý'), ('frustration_signal', 'Tín hiệu thất vọng'), ('give_up_signal', 'Tín hiệu bỏ cuộc'), ('response_time_outlier', 'Thời gian phản hồi bất thường'), ('struggle_detected', 'Phát hiện vật lộn'), ('scaffold_shown', 'Hiện scaffold'), ('scaffold_accepted', 'Chấp nhận scaffold'), ('cognitive_calibration_recorded', 'Ghi nhận tự đánh giá độ tự tin'), ('goal_set', 'Đặt mục tiêu'), ('goal_drift', 'Lệch mục tiêu'), ('reflection_submitted', 'Nộp reflection'), ('strategy_plan_set', 'Đặt kế hoạch chiến lược'), ('peer_benchmark_viewed', 'Xem so sánh peer'), ('reciprocal_teaching_started', 'Bắt đầu phiên dạy lẫn nhau'), ('reciprocal_teaching_rated', 'Đánh giá phiên dạy lẫn nhau'), ('coach_turn', 'Lượt hội thoại coach'), ('coach_nudge_sent', 'Coach gửi nudge'), ('emergency_detected', 'Phát hiện khủng hoảng'), ('counselor_responded', 'Counselor phản hồi'), ('emergency_resolved', 'Khủng hoảng được xử lý')], db_index=True, max_length=50),
        ),
    ]
