# Generated by Django 5.1.15 on 2026-04-18 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=False)),
                ("push_enabled", models.BooleanField(default=False)),
                (
                    "quiet_hours_start",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Local hour (0-23) when quiet hours start. Notifications still queued.",
                        null=True,
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Local hour (0-23) when quiet hours end.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_notification_preference",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("in_app", "Trong ứng dụng"),
                            ("email", "Email"),
                            ("push", "Push"),
                        ],
                        default="in_app",
                        max_length=16,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Thông tin"),
                            ("warning", "Cảnh báo"),
                            ("urgent", "Khẩn"),
                        ],
                        default="info",
                        max_length=16,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Domain category, e.g. coach, emergency, peer, goals.",
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("body", models.TextField(blank=True)),
                ("deep_link", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "read_at", "-created_at"],
                        name="palp_notifi_user_id_1f6e32_idx",
                    ),
                    models.Index(
                        fields=["category", "-created_at"],
                        name="palp_notifi_categor_3a552c_idx",
                    ),
                ],
            },
        ),
    ]
