# Generated by Django 5.1.15 on 2026-04-18 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BanditArm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=80)),
                ("title", models.CharField(max_length=160)),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arm-specific data the consumer needs (template_id, channel, …).",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "palp_bandit_arm",
            },
        ),
        migrations.CreateModel(
            name="BanditExperiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Đang chạy"),
                            ("paused", "Tạm dừng"),
                            ("archived", "Đã lưu trữ"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "reward_window_minutes",
                    models.PositiveIntegerField(
                        default=1440,
                        help_text="How long after a decision we still accept reward signals.",
                    ),
                ),
                (
                    "seed",
                    models.PositiveIntegerField(
                        default=42,
                        help_text="RNG seed for reproducible Thompson sampling in tests.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "palp_bandit_experiment",
            },
        ),
        migrations.CreateModel(
            name="BanditDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context_key", models.CharField(default="default", max_length=80)),
                (
                    "sampled_value",
                    models.FloatField(
                        help_text="Thompson sample drawn from the posterior at decision time."
                    ),
                ),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reward_window_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Reward signals after this time are ignored.",
                        null=True,
                    ),
                ),
                (
                    "arm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="bandit.banditarm",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bandit_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="bandit.banditexperiment",
                    ),
                ),
            ],
            options={
                "db_table": "palp_bandit_decision",
            },
        ),
        migrations.AddField(
            model_name="banditarm",
            name="experiment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arms",
                to="bandit.banditexperiment",
            ),
        ),
        migrations.CreateModel(
            name="BanditPosterior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "context_key",
                    models.CharField(
                        default="default",
                        help_text="Free-form context label (e.g. 'high_risk', 'morning').",
                        max_length=80,
                    ),
                ),
                ("alpha", models.FloatField(default=1.0)),
                ("beta", models.FloatField(default=1.0)),
                ("pulls", models.PositiveIntegerField(default=0)),
                ("rewards_sum", models.FloatField(default=0.0)),
                ("last_pulled_at", models.DateTimeField(blank=True, null=True)),
                ("last_rewarded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "arm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posteriors",
                        to="bandit.banditarm",
                    ),
                ),
            ],
            options={
                "db_table": "palp_bandit_posterior",
            },
        ),
        migrations.CreateModel(
            name="BanditReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.FloatField(
                        help_text="0.0 (no engagement) .. 1.0 (full engagement)."
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward",
                        to="bandit.banditdecision",
                    ),
                ),
            ],
            options={
                "db_table": "palp_bandit_reward",
            },
        ),
        migrations.AddIndex(
            model_name="banditdecision",
            index=models.Index(
                fields=["user", "-decided_at"], name="palp_bandit_user_id_d1e83d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banditdecision",
            index=models.Index(
                fields=["experiment", "-decided_at"],
                name="palp_bandit_experim_e598e5_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="banditarm",
            constraint=models.UniqueConstraint(
                fields=("experiment", "key"), name="uq_bandit_experiment_arm"
            ),
        ),
        migrations.AddIndex(
            model_name="banditposterior",
            index=models.Index(
                fields=["arm", "context_key"], name="palp_bandit_arm_id_80310e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="banditposterior",
            constraint=models.UniqueConstraint(
                fields=("arm", "context_key"), name="uq_bandit_arm_context"
            ),
        ),
    ]
