# Generated by Django 5.1.15 on 2026-04-19 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LinUCBArmState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context_key", models.CharField(default="default", max_length=80)),
                ("dimension", models.PositiveSmallIntegerField()),
                (
                    "matrix_a",
                    models.JSONField(
                        help_text="Serialised d-by-d matrix A_a (NumPy .tolist())."
                    ),
                ),
                (
                    "vector_b",
                    models.JSONField(
                        help_text="Serialised length-d vector b_a (NumPy .tolist())."
                    ),
                ),
                ("pulls", models.PositiveIntegerField(default=0)),
                ("rewards_sum", models.FloatField(default=0.0)),
                ("last_pulled_at", models.DateTimeField(blank=True, null=True)),
                ("last_rewarded_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "arm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linucb_states",
                        to="bandit.banditarm",
                    ),
                ),
            ],
            options={
                "db_table": "palp_bandit_linucb_state",
                "indexes": [
                    models.Index(
                        fields=["arm", "context_key"],
                        name="palp_bandit_arm_id_cc0afc_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("arm", "context_key"),
                        name="uq_bandit_linucb_arm_context",
                    )
                ],
            },
        ),
    ]
