# Generated by Django 5.1.15 on 2026-04-18 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FairnessAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_name",
                    models.CharField(
                        help_text="Logical name of the model/cluster being audited (matches ModelRegistry.name when applicable).",
                        max_length=120,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("classifier", "Classifier (DP / EOD)"),
                            ("clustering", "Clustering (concentration)"),
                            ("regression", "Regression (group MSE)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sensitive_attributes",
                    models.JSONField(
                        default=list,
                        help_text="List of attribute names checked (gender, region, economic_band, ...).",
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        default=dict,
                        help_text="Raw metric values: {disparate_impact_ratio, equalized_odds_diff, ...}",
                    ),
                ),
                (
                    "violations",
                    models.JSONField(
                        default=list,
                        help_text="List of {attr, value, observed, threshold} for failed checks.",
                    ),
                ),
                ("passed", models.BooleanField(default=False)),
                ("sample_size", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fairness_audits_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_fairness_audit",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["target_name", "-created_at"],
                        name="palp_fairne_target__126341_idx",
                    ),
                    models.Index(
                        fields=["passed", "-created_at"],
                        name="palp_fairne_passed_8b07b5_idx",
                    ),
                ],
            },
        ),
    ]
