# Generated by Django 5.1.15 on 2026-04-18 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("privacy", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="palp_audit__actor_i_a9e46c_idx",
            old_name="palp_audit_actor_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="palp_audit__target__29e719_idx",
            old_name="palp_audit_target_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="palp_audit__action_9b8408_idx",
            old_name="palp_audit_action_idx",
        ),
        migrations.RenameIndex(
            model_name="consentrecord",
            new_name="palp_consen_user_id_104be9_idx",
            old_name="palp_consent_user_purpose_idx",
        ),
    ]
