# Generated by Django 5.1.15 on 2026-04-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0002_rename_palp_audit_actor_idx_palp_audit__actor_i_a9e46c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentrecord',
            name='purpose',
            field=models.CharField(choices=[('academic', 'Dữ liệu học vụ lịch sử'), ('behavioral', 'Dữ liệu hành vi học tập'), ('inference', 'Dữ liệu suy luận (mastery, risk)'), ('behavioral_signals', 'Tín hiệu hành vi chi tiết'), ('cognitive_calibration', 'Tự đánh giá độ tự tin')], max_length=40),
        ),
        migrations.AlterField(
            model_name='consentrecord',
            name='version',
            field=models.CharField(default='1.1', max_length=20),
        ),
    ]
