# Generated by Django 5.1.15 on 2026-04-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("privacy", "0003_alter_consentrecord_purpose_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consentrecord",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("academic", "Dữ liệu học vụ lịch sử"),
                    ("behavioral", "Dữ liệu hành vi học tập"),
                    ("inference", "Dữ liệu suy luận (mastery, risk)"),
                    ("behavioral_signals", "Tín hiệu hành vi chi tiết"),
                    ("cognitive_calibration", "Tự đánh giá độ tự tin"),
                    ("peer_comparison", "So sánh ẩn danh trong cohort"),
                    ("peer_teaching", "Ghép cặp dạy nhau (reciprocal)"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="consentrecord",
            name="version",
            field=models.CharField(default="1.2", max_length=20),
        ),
    ]
