# Generated by Django 5.1.15 on 2026-04-18 12:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(max_length=80, unique=True)),
                (
                    "entity",
                    models.CharField(
                        help_text="Logical entity: student, class, concept, etc.",
                        max_length=40,
                    ),
                ),
                (
                    "source_table",
                    models.CharField(
                        help_text="DB table that materialises this feature group.",
                        max_length=80,
                    ),
                ),
                (
                    "features_json",
                    models.JSONField(
                        default=list,
                        help_text="List of feature spec dicts: [{name, dtype, description, ttl_seconds}].",
                    ),
                ),
                (
                    "online_store_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="If True, hot reads served from Redis online store.",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "palp_mlops_feature_view",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ModelRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(max_length=80, unique=True)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("bkt", "Bayesian Knowledge Tracing"),
                            ("dkt", "Deep Knowledge Tracing"),
                            ("risk_score", "Risk Score Composite"),
                            ("survival", "Dropout Survival"),
                            ("bandit", "Contextual Bandit"),
                            ("affect", "Affect Fusion"),
                            ("classifier_other", "Classifier (other)"),
                            ("clustering", "Clustering"),
                            ("embedding", "Embedding"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_models",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_mlops_registry",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semver",
                    models.CharField(
                        help_text="Semantic version, e.g. 1.0.0", max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("training", "Training"),
                            ("shadow", "Shadow (eval only)"),
                            ("staging", "Staging (internal)"),
                            ("production", "Production"),
                            ("deprecated", "Deprecated"),
                            ("archived", "Archived"),
                        ],
                        default="training",
                        max_length=20,
                    ),
                ),
                (
                    "artifact_uri",
                    models.CharField(
                        blank=True,
                        help_text="MLflow artifact URI, S3 key, or local file path.",
                        max_length=500,
                    ),
                ),
                (
                    "metrics_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Quantitative results: {auc: 0.78, brier: 0.12, ...}.",
                    ),
                ),
                (
                    "params_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Hyperparameters used for training.",
                    ),
                ),
                (
                    "training_data_ref",
                    models.CharField(
                        blank=True,
                        help_text="Pointer to training dataset version (Feast feature view + snapshot).",
                        max_length=300,
                    ),
                ),
                ("fairness_passed", models.BooleanField(default=False)),
                (
                    "epsilon_dp",
                    models.FloatField(
                        blank=True,
                        help_text="Differential-privacy epsilon spent during training (None if not DP).",
                        null=True,
                    ),
                ),
                (
                    "model_card_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to docs/model_cards/<name>.md.",
                        max_length=300,
                    ),
                ),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "promoted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promoted_model_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="mlops.modelregistry",
                    ),
                ),
            ],
            options={
                "db_table": "palp_mlops_version",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DriftReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField(default=django.utils.timezone.now)),
                ("drift_detected", models.BooleanField(default=False)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("none", "Không drift"),
                            ("minor", "Drift nhẹ"),
                            ("major", "Drift đáng kể"),
                            ("critical", "Drift nghiêm trọng — retrain ngay"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "feature_summary",
                    models.JSONField(
                        default=dict,
                        help_text="Per-feature drift score: {feat_name: {ks_p, drift_score}}.",
                    ),
                ),
                ("sample_size", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drift_reports",
                        to="mlops.modelversion",
                    ),
                ),
            ],
            options={
                "db_table": "palp_mlops_drift_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShadowComparison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField(default=django.utils.timezone.now)),
                ("n_predictions", models.PositiveIntegerField(default=0)),
                ("mean_abs_diff", models.FloatField(default=0.0)),
                ("p95_abs_diff", models.FloatField(default=0.0)),
                (
                    "agreement_pct",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage of predictions where shadow and baseline agree within ±0.05.",
                    ),
                ),
                ("divergence_summary", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "baseline_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shadow_runs_as_baseline",
                        to="mlops.modelversion",
                    ),
                ),
                (
                    "candidate_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shadow_runs_as_candidate",
                        to="mlops.modelversion",
                    ),
                ),
            ],
            options={
                "db_table": "palp_mlops_shadow_comparison",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="modelversion",
            index=models.Index(
                fields=["registry", "status"], name="palp_mlops__registr_6d2554_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="modelversion",
            constraint=models.UniqueConstraint(
                fields=("registry", "semver"), name="uq_mlops_version_registry_semver"
            ),
        ),
        migrations.AddIndex(
            model_name="driftreport",
            index=models.Index(
                fields=["model_version", "-created_at"],
                name="palp_mlops__model_v_f7da89_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="driftreport",
            index=models.Index(
                fields=["severity", "-created_at"],
                name="palp_mlops__severit_e527f7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shadowcomparison",
            index=models.Index(
                fields=["candidate_version", "-created_at"],
                name="palp_mlops__candida_06b9ff_idx",
            ),
        ),
    ]
