# Generated by Django 5.1.15 on 2026-04-18 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0002_concept_uq_concept_course_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composite', models.FloatField(help_text='0-100 composite. 0 = no risk, 100 = highest risk.')),
                ('dimensions', models.JSONField(default=dict, help_text='{academic, behavioral, engagement, psychological, metacognitive} -> 0..1')),
                ('components', models.JSONField(default=dict, help_text='Per-component sub-scores in 0..1 with the input data point used.')),
                ('explanation', models.JSONField(default=list, help_text='Top-N drivers as [{name, contribution_pct, hint}] for the XAI panel.')),
                ('weights_used', models.JSONField(default=dict, help_text='Snapshot of PALP_RISK_WEIGHTS at compute time (audit).')),
                ('sample_window_days', models.PositiveSmallIntegerField(default=14)),
                ('computed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('course', models.ForeignKey(blank=True, help_text='Optional — null means the score is course-agnostic.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='curriculum.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'palp_risk_score',
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['student', '-computed_at'], name='palp_risk_s_student_74eec2_idx'), models.Index(fields=['course', '-computed_at'], name='palp_risk_s_course__4169ef_idx')],
            },
        ),
    ]
