# Generated by Django 5.1.15 on 2026-04-18 12:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CanonicalSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canonical_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_event_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="canonical_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_canonical_session",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceFingerprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_hash",
                    models.CharField(
                        help_text="SHA-256 of (raw fingerprint + monthly salt). Rotates monthly.",
                        max_length=64,
                    ),
                ),
                (
                    "salt_month",
                    models.CharField(
                        help_text="YYYY-MM marker for the salt epoch used when hashing.",
                        max_length=7,
                    ),
                ),
                (
                    "user_agent_family",
                    models.CharField(
                        blank=True,
                        help_text="Coarse UA family (e.g. 'chrome-windows'), no version detail.",
                        max_length=80,
                    ),
                ),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "consent_given",
                    models.BooleanField(
                        default=False,
                        help_text="Snapshot of the user's device_fingerprinting consent at the time of registration.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_fingerprints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_device_fingerprint",
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_session_id", models.CharField(max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "canonical_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="device_sessions.canonicalsession",
                    ),
                ),
                (
                    "fingerprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_links",
                        to="device_sessions.devicefingerprint",
                    ),
                ),
            ],
            options={
                "db_table": "palp_session_link",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="canonicalsession",
            index=models.Index(
                fields=["user", "-started_at"], name="palp_canoni_user_id_07269f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicefingerprint",
            index=models.Index(
                fields=["user", "-last_seen_at"], name="palp_device_user_id_6bad29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicefingerprint",
            index=models.Index(
                fields=["device_hash", "salt_month"],
                name="palp_device_device__c2d8f3_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="devicefingerprint",
            constraint=models.UniqueConstraint(
                fields=("user", "device_hash", "salt_month"),
                name="uq_device_fingerprint_user_hash_month",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionlink",
            index=models.Index(
                fields=["canonical_session", "-created_at"],
                name="palp_sessio_canonic_9e9b1f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionlink",
            constraint=models.UniqueConstraint(
                fields=("raw_session_id",), name="uq_session_link_raw_id"
            ),
        ),
    ]
