# Generated by Django 5.1.15 on 2026-04-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_kpi_integrity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kpidefinition",
            name="source_events",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
