# Generated by Django 5.1.15 on 2026-04-19 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchProtocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField()),
                ("pi_name", models.CharField(blank=True, max_length=160)),
                ("pi_email", models.EmailField(blank=True, max_length=254)),
                ("irb_number", models.CharField(blank=True, max_length=80)),
                (
                    "data_purposes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of declared purposes (e.g. 'aied_2026_dkt_replication').",
                    ),
                ),
                (
                    "data_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Categories of data this protocol consumes (academic, behavioral, …).",
                    ),
                ),
                ("retention_months", models.PositiveSmallIntegerField(default=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Bản nháp"),
                            ("approved", "Đã phê duyệt"),
                            ("active", "Đang chạy"),
                            ("closed", "Đã đóng"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "palp_research_protocol",
            },
        ),
        migrations.CreateModel(
            name="ResearchParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("opted_in", "Đã tham gia"),
                            ("withdrawn", "Đã rút"),
                            ("declined", "Đã từ chối"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "consent_text_version",
                    models.CharField(
                        help_text="Snapshot of which consent-text version the student agreed to.",
                        max_length=20,
                    ),
                ),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="research.researchprotocol",
                    ),
                ),
            ],
            options={
                "db_table": "palp_research_participation",
                "indexes": [
                    models.Index(
                        fields=["protocol", "state"],
                        name="palp_resear_protoco_cfdb4c_idx",
                    ),
                    models.Index(
                        fields=["student", "-decided_at"],
                        name="palp_resear_student_ee07e6_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "protocol"),
                        name="uq_research_participation_student_protocol",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AnonymizedExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dataset_key",
                    models.CharField(
                        help_text="What dataset was exported (e.g. 'attempts_q1_2026').",
                        max_length=80,
                    ),
                ),
                ("record_count", models.PositiveIntegerField(default=0)),
                ("participant_count", models.PositiveIntegerField(default=0)),
                ("k_anonymity_value", models.PositiveSmallIntegerField(default=0)),
                ("k_anonymity_passed", models.BooleanField(default=False)),
                ("suppressed_columns", models.JSONField(blank=True, default=list)),
                (
                    "salt_id",
                    models.CharField(
                        blank=True,
                        help_text="Hash salt key reference; never store the salt itself here.",
                        max_length=80,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anonymized_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exports",
                        to="research.researchprotocol",
                    ),
                ),
            ],
            options={
                "db_table": "palp_research_anonymized_export",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["protocol", "-created_at"],
                        name="palp_resear_protoco_44e1cb_idx",
                    )
                ],
            },
        ),
    ]
