# Generated by Django 5.1.15 on 2026-04-19 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Datasheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataset_key", models.SlugField(max_length=120)),
                ("title", models.CharField(max_length=240)),
                ("motivation", models.TextField()),
                (
                    "composition",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{record_kind, count, schema, sensitive_attributes, missingness}",
                    ),
                ),
                ("collection_process", models.TextField(blank=True)),
                ("preprocessing", models.TextField(blank=True)),
                ("uses", models.JSONField(blank=True, default=list)),
                ("distribution", models.TextField(blank=True)),
                ("maintenance", models.TextField(blank=True)),
                ("licence", models.CharField(blank=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Bản nháp"),
                            ("reviewed", "Đã review"),
                            ("published", "Đã xuất bản"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="datasheets_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_publication_datasheet",
            },
        ),
        migrations.CreateModel(
            name="ModelCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_label",
                    models.SlugField(
                        help_text="e.g. 'sakt-numpy@0.1.0' or 'risk-composite@v1'.",
                        max_length=120,
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                ("intended_use", models.TextField()),
                ("out_of_scope_uses", models.JSONField(blank=True, default=list)),
                (
                    "training_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{description, size, period, license, link}",
                    ),
                ),
                ("evaluation_data", models.JSONField(blank=True, default=dict)),
                (
                    "performance",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-metric: {auc, rmse, accuracy, fairness_per_group}",
                    ),
                ),
                ("ethical_considerations", models.TextField(blank=True)),
                ("caveats", models.TextField(blank=True)),
                ("licence", models.CharField(blank=True, max_length=80)),
                ("authors", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Bản nháp"),
                            ("reviewed", "Đã review"),
                            ("published", "Đã xuất bản"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="model_cards_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_publication_model_card",
            },
        ),
        migrations.CreateModel(
            name="ReproducibilityKit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=240)),
                (
                    "benchmark_run_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Loose pointer to benchmarks.BenchmarkRun.",
                        null=True,
                    ),
                ),
                ("commit_hash", models.CharField(blank=True, max_length=80)),
                ("seed", models.PositiveIntegerField(default=42)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "datasheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repro_kits",
                        to="publication.datasheet",
                    ),
                ),
                (
                    "model_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="repro_kits",
                        to="publication.modelcard",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="repro_kits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_publication_repro_kit",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="datasheet",
            index=models.Index(
                fields=["status", "-updated_at"], name="palp_public_status_a6957c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modelcard",
            index=models.Index(
                fields=["status", "-updated_at"], name="palp_public_status_8beb24_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="modelcard",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "published")),
                fields=("model_label", "status"),
                name="uq_model_card_published_label",
            ),
        ),
    ]
