# Generated by Django 5.1.15 on 2026-04-18 12:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0002_concept_uq_concept_course_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('spaced_practice', 'Học dãn cách'), ('deep_focus_blocks', 'Khối tập trung sâu'), ('peer_teaching', 'Dạy bạn / được bạn dạy'), ('worked_examples', 'Đọc lời giải mẫu'), ('self_explanation', 'Tự giải thích bằng lời'), ('retrieval_practice', 'Truy hồi kiến thức'), ('other', 'Khác')], max_length=30)),
                ('rationale', models.TextField(blank=True, help_text='Why the student picked this strategy this week (optional).')),
                ('predicted_minutes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'palp_goal_strategy_plan',
                'ordering': ['weekly_goal', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('software_backend', 'Backend dev'), ('software_frontend', 'Frontend dev'), ('software_fullstack', 'Full-stack dev'), ('data', 'Data / Analytics'), ('ai_ml', 'AI / ML'), ('devops', 'DevOps / SRE'), ('security', 'Cybersecurity'), ('engineering', 'Kỹ thuật khác'), ('academia', 'Sau đại học / Nghiên cứu'), ('other', 'Khác')], default='other', max_length=30)),
                ('horizon_months', models.PositiveSmallIntegerField(default=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_goal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Career goal',
                'verbose_name_plural': 'Career goals',
                'db_table': 'palp_goal_career',
            },
        ),
        migrations.CreateModel(
            name='SemesterGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(help_text="Free-form semester id (e.g. '2026S1') consistent with curriculum.Enrollment.", max_length=10)),
                ('mastery_target', models.FloatField(default=0.7, help_text='Target average composite mastery for this course (0..1).')),
                ('completion_target_pct', models.PositiveSmallIntegerField(default=80, help_text='Target % of milestones completed by end of semester.')),
                ('intent', models.TextField(blank=True, help_text='Free-form motivation / why this matters to the student.')),
                ('started_at', models.DateField(default=django.utils.timezone.localdate)),
                ('target_end', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_goals', to='curriculum.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'palp_goal_semester',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyEffectiveness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text="Likert 1 (didn't help) to 5 (very effective)")),
                ('will_repeat', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('mastery_delta', models.FloatField(blank=True, help_text='Composite mastery change observed during the week (filled by service).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_effectiveness_ratings', to=settings.AUTH_USER_MODEL)),
                ('strategy_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='effectiveness', to='goals.strategyplan')),
            ],
            options={
                'db_table': 'palp_goal_strategy_effectiveness',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Monday (Asia/Ho_Chi_Minh) of the week this goal targets.')),
                ('target_minutes', models.PositiveIntegerField(default=300)),
                ('target_concept_ids', models.JSONField(blank=True, default=list, help_text='Optional list of curriculum.Concept ids the student plans to cover.')),
                ('target_micro_task_count', models.PositiveSmallIntegerField(default=10)),
                ('status', models.CharField(choices=[('planned', 'Đã lên kế hoạch'), ('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn thành'), ('drifted', 'Lệch kế hoạch'), ('abandoned', 'Bỏ')], default='planned', max_length=20)),
                ('drift_pct_last_check', models.FloatField(blank=True, help_text='Most recent (target - actual) / target ratio. >0.4 trips drift.', null=True)),
                ('drift_last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_goals', to='goals.semestergoal')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'palp_goal_weekly',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='TimeEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_minutes', models.PositiveIntegerField()),
                ('actual_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('estimate_error_pct', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalised_at', models.DateTimeField(blank=True, null=True)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_estimates', to='curriculum.concept')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_estimates', to=settings.AUTH_USER_MODEL)),
                ('weekly_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_estimates', to='goals.weeklygoal')),
            ],
            options={
                'db_table': 'palp_goal_time_estimate',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='strategyplan',
            name='weekly_goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_plans', to='goals.weeklygoal'),
        ),
        migrations.CreateModel(
            name='GoalReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('learned_text', models.TextField(blank=True, help_text='Tuần này bạn học được gì? (max ~500 từ)')),
                ('struggle_text', models.TextField(blank=True, help_text='Đâu là khó khăn lớn nhất tuần này?')),
                ('next_priority_text', models.TextField(blank=True, help_text='Tuần sau bạn ưu tiên điều gì?')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_reflections', to=settings.AUTH_USER_MODEL)),
                ('weekly_goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reflection', to='goals.weeklygoal')),
            ],
            options={
                'db_table': 'palp_goal_reflection',
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='EffortRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Likert 1 (very low effort) to 5 (very high effort)')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effort_ratings', to=settings.AUTH_USER_MODEL)),
                ('weekly_goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='effort_rating', to='goals.weeklygoal')),
            ],
            options={
                'db_table': 'palp_goal_effort_rating',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='semestergoal',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'semester'), name='uq_semester_goal_student_course_semester'),
        ),
        migrations.AddConstraint(
            model_name='strategyeffectiveness',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='ck_strategy_effectiveness_rating_1_5'),
        ),
        migrations.AddConstraint(
            model_name='weeklygoal',
            constraint=models.UniqueConstraint(fields=('student', 'week_start'), name='uq_weekly_goal_student_week'),
        ),
        migrations.AddConstraint(
            model_name='weeklygoal',
            constraint=models.CheckConstraint(condition=models.Q(('target_minutes__lte', 10080)), name='ck_weekly_goal_target_minutes_within_week'),
        ),
        migrations.AddIndex(
            model_name='timeestimate',
            index=models.Index(fields=['student', '-created_at'], name='palp_goal_t_student_71952b_idx'),
        ),
        migrations.AddConstraint(
            model_name='strategyplan',
            constraint=models.UniqueConstraint(fields=('weekly_goal', 'strategy'), name='uq_strategy_plan_per_week'),
        ),
        migrations.AddIndex(
            model_name='goalreflection',
            index=models.Index(fields=['student', '-week_start'], name='palp_goal_r_student_cc5891_idx'),
        ),
        migrations.AddConstraint(
            model_name='effortrating',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='ck_effort_rating_1_5'),
        ),
    ]
