# Generated by Django 5.1.15 on 2026-04-18 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0002_concept_uq_concept_course_order"),
        ("mlops", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DKTModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("semver", models.CharField(default="0.1.0", max_length=20)),
                (
                    "family",
                    models.CharField(
                        default="sakt-numpy",
                        help_text="Engine family (sakt-numpy, dkt-pytorch, akt-pytorch, …)",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("training", "Đang huấn luyện"),
                            ("shadow", "Đang shadow"),
                            ("staging", "Staging"),
                            ("production", "Production"),
                            ("retired", "Đã lưu trữ"),
                        ],
                        default="training",
                        max_length=16,
                    ),
                ),
                (
                    "hyperparameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Engine hyperparameters captured at training time.",
                    ),
                ),
                (
                    "metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Offline validation metrics (auc, accuracy, calibration).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mlops_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dkt_versions",
                        to="mlops.modelversion",
                    ),
                ),
            ],
            options={
                "db_table": "palp_dkt_model_version",
            },
        ),
        migrations.CreateModel(
            name="DKTPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "p_correct_next",
                    models.FloatField(
                        help_text="Probability the student answers the next item on this concept correctly."
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.5,
                        help_text="0..1 — how confident the model is (sequence length / coverage).",
                    ),
                ),
                (
                    "explanation",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Top-3 attention weights, recent attempts, prerequisite walks.",
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
                ("sequence_length", models.PositiveIntegerField(default=0)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dkt_predictions",
                        to="curriculum.concept",
                    ),
                ),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="dkt.dktmodelversion",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dkt_predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_dkt_prediction",
                "ordering": ["-computed_at"],
            },
        ),
        migrations.CreateModel(
            name="DKTAttemptLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_correct", models.BooleanField()),
                ("response_time_seconds", models.FloatField(blank=True, null=True)),
                ("hint_count", models.PositiveSmallIntegerField(default=0)),
                ("occurred_at", models.DateTimeField()),
                (
                    "source_attempt_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dkt_attempts",
                        to="curriculum.concept",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dkt_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_dkt_attempt_log",
                "ordering": ["student", "occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "occurred_at"],
                        name="palp_dkt_at_student_d9a412_idx",
                    ),
                    models.Index(
                        fields=["concept", "-occurred_at"],
                        name="palp_dkt_at_concept_bc6cd6_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="dktmodelversion",
            index=models.Index(
                fields=["status", "-created_at"], name="palp_dkt_mo_status_c3cb30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dktmodelversion",
            index=models.Index(
                fields=["family", "status"], name="palp_dkt_mo_family_cf3749_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dktmodelversion",
            constraint=models.UniqueConstraint(
                fields=("name", "semver"), name="uq_dkt_name_semver"
            ),
        ),
        migrations.AddIndex(
            model_name="dktprediction",
            index=models.Index(
                fields=["student", "concept"], name="palp_dkt_pr_student_104964_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dktprediction",
            index=models.Index(
                fields=["model_version", "-computed_at"],
                name="palp_dkt_pr_model_v_37563a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="dktprediction",
            constraint=models.UniqueConstraint(
                fields=("student", "concept", "model_version"),
                name="uq_dkt_student_concept_version",
            ),
        ),
    ]
