# Generated by Django 5.1.15 on 2026-04-18 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ai_coach_local",
                    models.BooleanField(
                        default=True,
                        help_text="Local LLM dialog. PII never leaves infrastructure.",
                    ),
                ),
                (
                    "ai_coach_cloud",
                    models.BooleanField(
                        default=False,
                        help_text="Cloud LLM dialog (Anthropic/OpenAI). Requires explicit opt-in.",
                    ),
                ),
                (
                    "share_emergency_contact",
                    models.BooleanField(
                        default=False,
                        help_text="Allow Emergency Pipeline to contact your emergency contact.",
                    ),
                ),
                (
                    "cooldown_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="If set, coach refuses messages until this time (e.g. after 3 jailbreak attempts).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_consent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_coach_consent",
            },
        ),
        migrations.CreateModel(
            name="CoachConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Đang mở"),
                            ("ended", "Đã kết thúc"),
                            ("system_closed", "Hệ thống đóng (cooldown / safety)"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("last_intent", models.CharField(blank=True, max_length=40)),
                ("turn_count", models.PositiveIntegerField(default=0)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coach_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_coach_conversation",
            },
        ),
        migrations.CreateModel(
            name="CoachTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turn_number", models.PositiveIntegerField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Sinh viên"),
                            ("assistant", "Coach"),
                            ("system", "Hệ thống"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("intent", models.CharField(blank=True, max_length=40)),
                ("llm_provider", models.CharField(blank=True, max_length=20)),
                ("llm_model", models.CharField(blank=True, max_length=60)),
                (
                    "safety_flags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of safety findings for this turn (refusal, jailbreak, etc).",
                    ),
                ),
                ("refusal_triggered", models.BooleanField(default=False)),
                ("emergency_triggered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="coach.coachconversation",
                    ),
                ),
            ],
            options={
                "db_table": "palp_coach_turn",
                "ordering": ["conversation", "turn_number"],
            },
        ),
        migrations.CreateModel(
            name="CoachAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(blank=True, max_length=64)),
                ("intent", models.CharField(blank=True, max_length=40)),
                ("llm_provider", models.CharField(blank=True, max_length=20)),
                ("llm_model", models.CharField(blank=True, max_length=60)),
                ("tokens_in", models.PositiveIntegerField(default=0)),
                ("tokens_out", models.PositiveIntegerField(default=0)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("tools_called", models.JSONField(blank=True, default=list)),
                ("safety_flags", models.JSONField(blank=True, default=list)),
                ("pii_tokens_count", models.PositiveIntegerField(default=0)),
                ("canary_check_passed", models.BooleanField(default=True)),
                ("hallucination_findings", models.JSONField(blank=True, default=list)),
                ("refusal_triggered", models.BooleanField(default=False)),
                ("emergency_triggered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "turn",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit",
                        to="coach.coachturn",
                    ),
                ),
            ],
            options={
                "db_table": "palp_coach_audit",
            },
        ),
        migrations.AddIndex(
            model_name="coachconversation",
            index=models.Index(
                fields=["student", "status"], name="palp_coach__student_64deaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coachconversation",
            index=models.Index(
                fields=["student", "-started_at"], name="palp_coach__student_b4c187_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="coachturn",
            constraint=models.UniqueConstraint(
                fields=("conversation", "turn_number"), name="uq_coach_turn_seq"
            ),
        ),
        migrations.AddIndex(
            model_name="coachauditlog",
            index=models.Index(
                fields=["llm_provider", "-created_at"],
                name="palp_coach__llm_pro_c91fc3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coachauditlog",
            index=models.Index(
                fields=["refusal_triggered", "-created_at"],
                name="palp_coach__refusal_22cd31_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coachauditlog",
            index=models.Index(
                fields=["emergency_triggered", "-created_at"],
                name="palp_coach__emergen_a4b099_idx",
            ),
        ),
    ]
