# Generated by Django 5.1.15 on 2026-04-18 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_alter_user_groups_alter_user_is_active_and_more"),
        ("curriculum", "0002_concept_uq_concept_course_order"),
        ("fairness", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PeerCohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ability_band_label", models.CharField(max_length=32)),
                ("members_count", models.PositiveIntegerField(default=0)),
                (
                    "centroid",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="K-means centroid vector in concept-mastery space.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fairness_audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="peer_cohorts",
                        to="fairness.fairnessaudit",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="peer_cohorts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_cohorts",
                        to="accounts.studentclass",
                    ),
                ),
            ],
            options={
                "db_table": "palp_peer_cohort",
            },
        ),
        migrations.CreateModel(
            name="PeerConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frontier_mode",
                    models.BooleanField(
                        default=True,
                        help_text="Past-self vs current-self comparison. No peer data involved.",
                    ),
                ),
                (
                    "peer_comparison",
                    models.BooleanField(
                        default=False,
                        help_text="Anonymous percentile band within the same-ability cohort.",
                    ),
                ),
                (
                    "peer_teaching",
                    models.BooleanField(
                        default=False,
                        help_text="Eligible for reciprocal teaching matches and sessions.",
                    ),
                ),
                (
                    "prompt_shown_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time the 4-week opt-in prompt was surfaced to the student.",
                        null=True,
                    ),
                ),
                ("last_revoked_purpose", models.CharField(blank=True, max_length=40)),
                ("last_revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_consent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_peer_consent",
            },
        ),
        migrations.CreateModel(
            name="ReciprocalPeerMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "compatibility_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Composite score; higher = stronger reciprocity.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Đang chờ đồng ý"),
                            ("active", "Đang hoạt động"),
                            ("archived", "Đã lưu trữ"),
                            ("declined", "Đã từ chối"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cohort",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="peer.peercohort",
                    ),
                ),
                (
                    "concept_a_to_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches_as_taught_a_to_b",
                        to="curriculum.concept",
                    ),
                ),
                (
                    "concept_b_to_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches_as_taught_b_to_a",
                        to="curriculum.concept",
                    ),
                ),
                (
                    "student_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_matches_as_a",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_matches_as_b",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_peer_match",
            },
        ),
        migrations.CreateModel(
            name="TeachingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "current_round",
                    models.CharField(
                        choices=[
                            ("brief", "Giới thiệu"),
                            ("a_teaches_x", "A dạy X cho B"),
                            ("b_asks", "B hỏi rõ"),
                            ("b_teaches_y", "B dạy Y cho A"),
                            ("a_asks", "A hỏi rõ"),
                            ("mutual_rating", "Đánh giá lẫn nhau"),
                            ("follow_up", "Bài tập theo dõi"),
                            ("completed", "Hoàn thành"),
                        ],
                        default="brief",
                        max_length=20,
                    ),
                ),
                (
                    "a_rating_by_b",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "b_rating_by_a",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("a_mastery_delta_after", models.FloatField(blank=True, null=True)),
                ("b_mastery_delta_after", models.FloatField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="peer.reciprocalpeermatch",
                    ),
                ),
            ],
            options={
                "db_table": "palp_peer_teaching_session",
            },
        ),
        migrations.CreateModel(
            name="HerdCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("medium", "Trung bình"),
                            ("high", "Cao"),
                            ("critical", "Nghiêm trọng"),
                        ],
                        default="medium",
                        max_length=16,
                    ),
                ),
                ("mean_risk_score", models.FloatField(default=0.0)),
                (
                    "behaviour_summary",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Mean focus minutes, missed milestones, give-up count, dismissed nudges, weekly login days for the cluster (14-day window).",
                    ),
                ),
                ("flagged_for_review", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewer_notes", models.TextField(blank=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fairness_audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="herd_clusters",
                        to="fairness.fairnessaudit",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="herd_clusters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_herd_clusters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="herd_clusters",
                        to="accounts.studentclass",
                    ),
                ),
            ],
            options={
                "db_table": "palp_peer_herd_cluster",
                "indexes": [
                    models.Index(
                        fields=["student_class", "-detected_at"],
                        name="palp_peer_h_student_36c83d_idx",
                    ),
                    models.Index(
                        fields=["is_resolved", "severity"],
                        name="palp_peer_h_is_reso_9bb64c_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="peercohort",
            index=models.Index(
                fields=["student_class", "is_active"],
                name="palp_peer_c_student_2c0994_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reciprocalpeermatch",
            index=models.Index(
                fields=["student_a", "status"], name="palp_peer_m_student_f43a4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reciprocalpeermatch",
            index=models.Index(
                fields=["student_b", "status"], name="palp_peer_m_student_0b2ecc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reciprocalpeermatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("student_a", models.F("student_b")), _negated=True),
                name="peer_match_distinct_students",
            ),
        ),
        migrations.AddIndex(
            model_name="teachingsession",
            index=models.Index(
                fields=["match", "-started_at"], name="palp_peer_t_match_i_c3fa16_idx"
            ),
        ),
    ]
