# Generated by Django 5.1.15 on 2026-04-19 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExplanationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("risk_score", "Composite risk"),
                            ("dkt_prediction", "DKT next-correct"),
                            ("fsrs_review", "FSRS interval"),
                            ("bandit_decision", "Bandit arm choice"),
                            ("other", "Khác"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("shap_lite", "SHAP-lite (additive)"),
                            ("attention", "Attention weights"),
                            ("counterfactual", "Counterfactual"),
                            ("rule_trace", "Rule trace"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "target_object_id",
                    models.CharField(
                        blank=True,
                        help_text="Loose pointer to the predicted thing (concept_id, decision_id, …).",
                        max_length=64,
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        help_text="Short Vietnamese sentence the UI can show as the headline.",
                        max_length=255,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full explanation payload (contributions, attention rows, ...).",
                    ),
                ),
                ("confidence", models.FloatField(default=0.5)),
                (
                    "base_value",
                    models.FloatField(
                        blank=True,
                        help_text="Population baseline (mean of the score) for additive methods.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="explanations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_xai_explanation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CounterfactualScenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_key", models.CharField(max_length=80)),
                ("current_value", models.FloatField()),
                ("target_value", models.FloatField()),
                ("expected_delta", models.FloatField()),
                (
                    "feasibility",
                    models.FloatField(
                        default=0.5,
                        help_text="0..1 — how realistic is it for the student to make this change.",
                    ),
                ),
                ("actionable_hint", models.CharField(blank=True, max_length=240)),
                (
                    "explanation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counterfactuals",
                        to="explainability.explanationrecord",
                    ),
                ),
            ],
            options={
                "db_table": "palp_xai_counterfactual",
            },
        ),
        migrations.CreateModel(
            name="FeatureContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_key", models.CharField(max_length=80)),
                ("raw_value", models.FloatField(blank=True, null=True)),
                (
                    "contribution",
                    models.FloatField(
                        help_text="Signed contribution to the prediction. Positive = pushes UP."
                    ),
                ),
                ("rank", models.PositiveIntegerField(default=0)),
                (
                    "explanation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="explainability.explanationrecord",
                    ),
                ),
            ],
            options={
                "db_table": "palp_xai_feature_contribution",
                "ordering": ["explanation", "rank"],
            },
        ),
        migrations.AddIndex(
            model_name="explanationrecord",
            index=models.Index(
                fields=["subject", "kind", "-created_at"],
                name="palp_xai_ex_subject_e08b3d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="explanationrecord",
            index=models.Index(
                fields=["kind", "method", "-created_at"],
                name="palp_xai_ex_kind_ffea8a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="counterfactualscenario",
            index=models.Index(
                fields=["explanation", "-expected_delta"],
                name="palp_xai_co_explana_2fb446_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="featurecontribution",
            index=models.Index(
                fields=["explanation", "rank"], name="palp_xai_fe_explana_cc558e_idx"
            ),
        ),
    ]
