# Generated by Django 5.1.15 on 2026-04-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="concept",
            constraint=models.UniqueConstraint(
                fields=("course", "order"), name="uq_concept_course_order"
            ),
        ),
    ]
