# Generated by Django 5.1.15 on 2026-04-18 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("experiments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CausalExperiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pre_registration",
                    models.TextField(
                        help_text="Frozen statement of hypothesis + primary outcome + analysis method, captured BEFORE the experiment is started. Modifying this after ``locked_at`` is set requires a new amendment."
                    ),
                ),
                (
                    "primary_outcome_metric",
                    models.CharField(
                        help_text="Name of the KPI used as primary outcome.",
                        max_length=120,
                    ),
                ),
                (
                    "secondary_outcomes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of additional outcome metric names.",
                    ),
                ),
                (
                    "outcome_kind",
                    models.CharField(
                        choices=[
                            ("binary", "Binary (0/1)"),
                            ("continuous", "Continuous"),
                            ("time_to_event", "Time-to-event"),
                        ],
                        default="continuous",
                        max_length=20,
                    ),
                ),
                (
                    "randomization_unit",
                    models.CharField(
                        choices=[
                            ("student", "Per-student (default)"),
                            ("class", "Per-class (cluster RCT)"),
                            ("cohort", "Per-cohort"),
                            ("time_slice", "Time-slice (switchback)"),
                        ],
                        default="student",
                        max_length=20,
                    ),
                ),
                (
                    "cuped_covariate",
                    models.CharField(
                        blank=True,
                        help_text="Optional pre-period metric used for CUPED variance reduction.",
                        max_length=120,
                    ),
                ),
                (
                    "expected_effect_size",
                    models.FloatField(
                        blank=True,
                        help_text="Effect size used in the power analysis.",
                        null=True,
                    ),
                ),
                ("target_sample_per_arm", models.PositiveIntegerField(default=0)),
                (
                    "irb_reference",
                    models.CharField(
                        blank=True,
                        help_text="IRB approval ID. Required for studies with human-subjects causal claims.",
                        max_length=80,
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when ``lock_pre_registration()`` is called. After this, any change to hypothesis/outcome/method must use ``amendments_log``.",
                        null=True,
                    ),
                ),
                (
                    "amendments_log",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Append-only list of {when, by, reason, diff} after lock.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "experiment",
                    models.OneToOneField(
                        help_text="Underlying A/B experiment that supplies variants + assignments.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="causal_layer",
                        to="experiments.experiment",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="causal_pre_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_causal_experiment",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CausalEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estimator",
                    models.CharField(
                        choices=[
                            ("naive", "Naive difference-in-means"),
                            ("ipw", "Inverse Propensity Weighting"),
                            ("doubly_robust", "Doubly-Robust"),
                            ("cuped_naive", "Naive + CUPED variance reduction"),
                            ("uplift_tree", "Uplift forest (causalml)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("n_treatment", models.PositiveIntegerField(default=0)),
                ("n_control", models.PositiveIntegerField(default=0)),
                ("ate", models.FloatField(blank=True, null=True)),
                ("ate_ci_low", models.FloatField(blank=True, null=True)),
                ("ate_ci_high", models.FloatField(blank=True, null=True)),
                ("p_value", models.FloatField(blank=True, null=True)),
                (
                    "estimate_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Estimator-specific extras (heterogeneity table, std errors, ...).",
                    ),
                ),
                (
                    "fairness_audit_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="FK-style reference to fairness.FairnessAudit so we can prove subgroup fairness was checked alongside the causal claim. Plain integer to avoid hard-coupling apps.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="causal.causalexperiment",
                    ),
                ),
            ],
            options={
                "db_table": "palp_causal_evaluation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["experiment", "estimator"],
                        name="palp_causal_experim_413a96_idx",
                    )
                ],
            },
        ),
    ]
