# Generated by Django 5.1.15 on 2026-04-18 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("coach", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("parent", "Phụ huynh"),
                            ("sibling", "Anh chị em"),
                            ("friend", "Bạn"),
                            ("counselor", "Cố vấn"),
                            ("other", "Khác"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                ("consent_given", models.BooleanField(default=False)),
                ("consent_given_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contact",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_emergency_contact",
            },
        ),
        migrations.CreateModel(
            name="EmergencyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("medium", "Trung bình"),
                            ("high", "Cao"),
                            ("critical", "Nguy cấp"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Đang mở"),
                            ("acknowledged", "Counselor đã xác nhận"),
                            ("resolved", "Đã giải quyết"),
                            ("escalated", "Đã leo thang tiếp"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("detected_keywords", models.JSONField(blank=True, default=list)),
                ("detector_score", models.FloatField(default=0.0)),
                ("detector_notes", models.TextField(blank=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sla_target_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this event must be acknowledged by a counselor (15-min SLA).",
                        null=True,
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("follow_up_24h_at", models.DateTimeField(blank=True, null=True)),
                ("follow_up_48h_at", models.DateTimeField(blank=True, null=True)),
                ("follow_up_72h_at", models.DateTimeField(blank=True, null=True)),
                ("contacted_emergency_contact", models.BooleanField(default=False)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_emergencies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "triggering_turn",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_events",
                        to="coach.coachturn",
                    ),
                ),
            ],
            options={
                "db_table": "palp_emergency_event",
            },
        ),
        migrations.CreateModel(
            name="CounselorQueueEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("queued", "Trong hàng đợi"),
                            ("viewed", "Đã xem"),
                            ("accepted", "Đã nhận"),
                            ("declined", "Đã từ chối"),
                            ("expired", "Đã hết hạn"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counselor_queue_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_entries",
                        to="emergency.emergencyevent",
                    ),
                ),
            ],
            options={
                "db_table": "palp_counselor_queue",
            },
        ),
        migrations.AddIndex(
            model_name="emergencyevent",
            index=models.Index(
                fields=["status", "-detected_at"], name="palp_emerge_status_3c0eae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyevent",
            index=models.Index(
                fields=["severity", "-detected_at"],
                name="palp_emerge_severit_0bec4f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyevent",
            index=models.Index(
                fields=["student", "-detected_at"],
                name="palp_emerge_student_590849_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="counselorqueueentry",
            index=models.Index(
                fields=["counselor", "state", "-queued_at"],
                name="palp_counse_counsel_ff3a00_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="counselorqueueentry",
            index=models.Index(
                fields=["event", "state"], name="palp_counse_event_i_96af52_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="counselorqueueentry",
            constraint=models.UniqueConstraint(
                fields=("event", "counselor"), name="uq_counselor_queue_event_counselor"
            ),
        ),
    ]
