# Generated by Django 5.1.15 on 2026-04-19 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0002_concept_uq_concept_course_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("new", "Mới"),
                            ("learning", "Đang học"),
                            ("review", "Đang ôn"),
                            ("relearning", "Học lại"),
                            ("suspended", "Tạm dừng"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "stability",
                    models.FloatField(
                        default=1.0,
                        help_text="FSRS stability (days). Higher = forgets slower.",
                    ),
                ),
                (
                    "difficulty",
                    models.FloatField(
                        default=5.0,
                        help_text="FSRS difficulty 1..10. Higher = harder for THIS student.",
                    ),
                ),
                ("last_review_at", models.DateTimeField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("review_count", models.PositiveIntegerField(default=0)),
                ("lapse_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_items",
                        to="curriculum.concept",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "palp_spacedrep_item",
            },
        ),
        migrations.CreateModel(
            name="ReviewLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Quên hẳn"), (2, "Vất vả"), (3, "Tốt"), (4, "Dễ")]
                    ),
                ),
                ("response_time_seconds", models.FloatField(blank=True, null=True)),
                ("pre_stability", models.FloatField()),
                ("pre_difficulty", models.FloatField()),
                ("post_stability", models.FloatField()),
                ("post_difficulty", models.FloatField()),
                ("interval_days", models.FloatField()),
                ("retrievability_at_review", models.FloatField(default=0.0)),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="spacedrep.reviewitem",
                    ),
                ),
            ],
            options={
                "db_table": "palp_spacedrep_log",
                "ordering": ["item", "reviewed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="reviewitem",
            index=models.Index(
                fields=["student", "due_at"], name="palp_spaced_student_f28bdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewitem",
            index=models.Index(
                fields=["student", "state"], name="palp_spaced_student_2013cd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewitem",
            constraint=models.UniqueConstraint(
                fields=("student", "concept"), name="uq_review_item_student_concept"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewlog",
            index=models.Index(
                fields=["item", "-reviewed_at"], name="palp_spaced_item_id_2580af_idx"
            ),
        ),
    ]
