# Generated by Django 5.1.15 on 2026-04-18 03:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Dot-namespaced identifier, e.g. 'pedagogy.adaptive_difficulty_v2'.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Master switch. When False the flag is OFF for everyone.",
                    ),
                ),
                (
                    "rollout_pct",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="0-100. Deterministic per user id when enabled=True.",
                    ),
                ),
                (
                    "rules_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional targeting: {'roles': ['student'], 'class_ids': [12], 'env': ['staging']}.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "palp_feature_flag",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FeatureFlagAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("before", models.JSONField(default=dict)),
                ("after", models.JSONField(default=dict)),
                (
                    "when",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flag_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "flag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_entries",
                        to="featureflags.featureflag",
                    ),
                ),
            ],
            options={
                "db_table": "palp_feature_flag_audit",
                "ordering": ["-when"],
            },
        ),
    ]
