# Generated by Django 5.1.15 on 2026-04-18 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptive', '0001_initial'),
        ('curriculum', '0002_concept_uq_concept_course_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='masterystate',
            name='p_mastery_v2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MetacognitiveJudgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_pre', models.PositiveSmallIntegerField(help_text='Likert 1 (very unsure) to 5 (very sure) recorded before submit.')),
                ('actual_correct', models.BooleanField(blank=True, null=True)),
                ('calibration_error', models.FloatField(blank=True, help_text='|normalised(confidence) - actual_correct| in [0,1]. 0 = perfectly calibrated.', null=True)),
                ('judgment_type', models.CharField(choices=[('JOL', 'Judgment of Learning (sau học, trước test)'), ('FOK', 'Feeling of Knowing (trước recall)'), ('EOL', 'Ease of Learning (trước nhiệm vụ mới)')], default='JOL', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metacognitive_judgments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metacognitive_judgments', to='curriculum.microtask')),
                ('task_attempt', models.OneToOneField(blank=True, help_text='Linked once the attempt is recorded; nullable so judgments made before submit can still be persisted optimistically.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metacognitive_judgment', to='adaptive.taskattempt')),
            ],
            options={
                'db_table': 'palp_metacog_judgment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', '-created_at'], name='idx_metacog_student'), models.Index(fields=['task', 'judgment_type'], name='idx_metacog_task_type')],
                'constraints': [models.CheckConstraint(condition=models.Q(('confidence_pre__gte', 1), ('confidence_pre__lte', 5)), name='ck_metacog_confidence_1_5'), models.CheckConstraint(condition=models.Q(('calibration_error__isnull', True), models.Q(('calibration_error__gte', 0), ('calibration_error__lte', 1)), _connector='OR'), name='ck_metacog_calibration_0_1')],
            },
        ),
    ]
