# Generated by Django 5.1.15 on 2026-04-18 12:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(db_index=True)),
                ('total_focus_minutes', models.FloatField(default=0.0)),
                ('total_idle_minutes', models.FloatField(default=0.0)),
                ('avg_focus_score', models.FloatField(default=0.0)),
                ('avg_frustration_score', models.FloatField(default=0.0)),
                ('total_tab_switches', models.PositiveIntegerField(default=0)),
                ('total_give_up_count', models.PositiveIntegerField(default=0)),
                ('total_struggle_count', models.PositiveIntegerField(default=0)),
                ('total_hint_count', models.PositiveIntegerField(default=0)),
                ('sessions_count', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'palp_behavior_score',
                'ordering': ['-day'],
                'indexes': [models.Index(fields=['student', '-day'], name='palp_behavi_student_65efb7_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'day'), name='uq_behavior_score_student_day')],
            },
        ),
        migrations.CreateModel(
            name='SignalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_session_id', models.UUIDField(blank=True, db_index=True, help_text='Optional link to device_sessions.CanonicalSession; null when sensing fires before stitching is wired.', null=True)),
                ('raw_session_id', models.CharField(blank=True, help_text='Frontend-supplied session id; useful for forensics before stitching backfills canonical_session_id.', max_length=120)),
                ('window_start', models.DateTimeField(db_index=True)),
                ('window_end', models.DateTimeField()),
                ('focus_minutes', models.FloatField(default=0.0)),
                ('idle_minutes', models.FloatField(default=0.0)),
                ('tab_switches', models.PositiveIntegerField(default=0)),
                ('hint_count', models.PositiveIntegerField(default=0)),
                ('frustration_score', models.FloatField(default=0.0, help_text='0-1 composite from frustration_signal events in the window.')),
                ('give_up_count', models.PositiveIntegerField(default=0)),
                ('response_time_outliers', models.PositiveIntegerField(default=0)),
                ('struggle_count', models.PositiveIntegerField(default=0)),
                ('raw_event_count', models.PositiveIntegerField(default=0)),
                ('last_event_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'palp_signal_session',
                'ordering': ['-window_start'],
                'indexes': [models.Index(fields=['student', '-window_start'], name='palp_signal_student_feaccb_idx'), models.Index(fields=['canonical_session_id', '-window_start'], name='palp_signal_canonic_c6f5eb_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'raw_session_id', 'window_start'), name='uq_signal_session_student_session_window')],
            },
        ),
    ]
