# Generated by Django 5.1.15 on 2026-04-18 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("curriculum", "0002_concept_uq_concept_course_order"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrerequisiteEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "strength",
                    models.FloatField(
                        default=0.7,
                        help_text="0..1 strength of the dependency (higher = more critical).",
                    ),
                ),
                (
                    "dependency_type",
                    models.CharField(
                        choices=[
                            ("required", "Bắt buộc trước"),
                            ("helpful", "Hữu ích"),
                            ("notation", "Ký hiệu / quy ước"),
                            ("context", "Bối cảnh"),
                        ],
                        default="required",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "edge",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kg_metadata",
                        to="curriculum.conceptprerequisite",
                    ),
                ),
            ],
            options={
                "db_table": "palp_kg_prerequisite_edge",
            },
        ),
        migrations.CreateModel(
            name="RootCauseSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "walk_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="{'visited': [{concept_id, name, p_mastery, depth}], 'edges': [{from, to, strength, type}], 'recommendation': str}",
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="root_cause_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_concept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="root_cause_targets",
                        to="curriculum.concept",
                    ),
                ),
                (
                    "weakest_prerequisite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="root_cause_weakest_for",
                        to="curriculum.concept",
                    ),
                ),
            ],
            options={
                "db_table": "palp_kg_root_cause_snapshot",
                "indexes": [
                    models.Index(
                        fields=["student", "-computed_at"],
                        name="palp_kg_roo_student_32666b_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "target_concept"),
                        name="uq_root_cause_student_target",
                    )
                ],
            },
        ),
    ]
