# Generated by Django 5.1.15 on 2026-04-19 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EpsilonBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.SlugField(max_length=120)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "epsilon_total",
                    models.FloatField(
                        default=1.0,
                        help_text="Maximum cumulative ε allowed within the period.",
                    ),
                ),
                ("epsilon_spent", models.FloatField(default=0.0)),
                ("description", models.CharField(blank=True, max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "palp_dp_epsilon_budget",
                "indexes": [
                    models.Index(
                        fields=["scope", "-period_start"],
                        name="palp_dp_eps_scope_2e2c61_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "period_start"),
                        name="uq_dp_epsilon_scope_period",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DPQueryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mechanism",
                    models.CharField(
                        choices=[("laplace", "Laplace"), ("gaussian", "Gaussian")],
                        default="laplace",
                        max_length=16,
                    ),
                ),
                ("query_kind", models.CharField(max_length=80)),
                ("epsilon_spent", models.FloatField()),
                ("sensitivity", models.FloatField(default=1.0)),
                ("raw_value", models.FloatField()),
                ("noisy_value", models.FloatField()),
                ("sample_size", models.PositiveIntegerField(default=0)),
                ("notes", models.CharField(blank=True, max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dp_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="queries",
                        to="privacy_dp.epsilonbudget",
                    ),
                ),
            ],
            options={
                "db_table": "palp_dp_query_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["budget", "-created_at"],
                        name="palp_dp_que_budget__26a5d1_idx",
                    ),
                    models.Index(
                        fields=["query_kind", "-created_at"],
                        name="palp_dp_que_query_k_98a511_idx",
                    ),
                ],
            },
        ),
    ]
